---
- hosts: all
  tasks:
    - name: installing httpd package server
      yum: name=httpd state=installed
    - name: copying the index file from ansible server to node/remote servers
      copy: src=/root/.jenkins/workspace/apche_webserver/index.html dest=/var/www/html/index.html
